CXX = g++
CXXFLAGS = -lsqlite3 -std=c++11

all: SQL_insert_test01

SQL_insert_test01: ../recipe.o ../groc_db.o SQL_insert_test01.cpp
	g++ $(CXXFLAGS) ../recipe.o ../groc_db.o SQL_insert_test01.cpp -o SQL_insert_test01

../recipe.o: ../recipe.cpp
	g++ ../recipe.cpp

../groc_db.o: ../groc_db.cpp
	g++ $(CXXFLAGS) ../groc_db.cpp












